
import { Providers } from "./GlobalRedux/provoder";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head className="" ></head>
      <body>
        <h1 className="px-4 bg-fuchsia-800 py-2">this is counter with toolkit </h1>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};
export default RootLayout;